### ISSUE TITLE
Long record values are corrupted during create/update (e.g. SPF)

### ISSUE THREAD

**Issue by timohirt** [timohirt/terraform-provider-hetznerdns#13]
When a DNS record with a long value is created or updated, quotes are inserted in the value. I used the request below to create a record.

```
curl -X "POST" "https://dns.hetzner.com/api/v1/records" \
     -H 'Content-Type: application/json' \
     -H "Auth-API-Token: $HETZNER_DNS_API_TOKEN" \
     -d '{
  "value": "v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhTo5UKCr5cHhmne2ZZX5swOlNP794OWVxmhPt0hdsMaYQ9d1uJ86u4qdwuu6M7DCV/pRg4+XdSAeSGOm0O6k+oBSrkzk+ijGuCjDSKNrCsDEJwyVBkbnat2mDtKednRWolIZmUP1Rs9pNOKcq8FJI52Ewc5imeX1T0agawtRB6Q0RoJOoEo4Y0fNeDOFTcn9YE7qgl2dKjo7ng8Ty/na8IBMqIjbzVaKpKQnIKfCwopO4cF7fzDHuqxSCxD3CAidgUbdHarwgC5M7d43GnWmGwgA5PhnE0iUNASbbfStY4PSHXeq3+FO2euC348/Vk6WOE9tFTEFiF/oMq5qgm5yEwIDAQAB",
  "ttl": 3600,
  "type": "TXT",
  "name": "dkim_2",
  "zone_id": "rMu2waTJP77777777777"
}'
```

The value is one string. Now, let's take a look at the response.

```
{
  "record": {
    "id": "c03bdbf918bc9984090242a9da1d240e",
    "type": "TXT",
    "name": "dkim_2",
    "value": "\"v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhTo5UKCr5cHhmne2ZZX5swOlNP794OWVxmhPt0hdsMaYQ9d1uJ86u4qdwuu6M7DCV/pRg4+XdSAeSGOm0O6k+oBSrkzk+ijGuCjDSKNrCsDEJwyVBkbnat2mDtKednRWolIZmUP1Rs9pNOKcq8FJI52Ewc5imeX1T0agawtRB6Q0RoJOoEo4Y0fNeDOFTcn9Y\" \"E7qgl2dKjo7ng8Ty/na8IBMqIjbzVaKpKQnIKfCwopO4cF7fzDHuqxSCxD3CAidgUbdHarwgC5M7d43GnWmGwgA5PhnE0iUNASbbfStY4PSHXeq3+FO2euC348/Vk6WOE9tFTEFiF/oMq5qgm5yEwIDAQAB\" ",
    "ttl": 3600,
    "zone_id": "rMu2waTJPbHr45psPMZxHV",
    "created": "2020-09-03 20:29:53.973 +0000 UTC",
    "modified": "2020-09-03 20:29:53.973 +0000 UTC"
  }
}
```

There are 4 additional quotes now. It seems that the value was split into two values and this resulted into an invalid DKIM record:

![image](https://user-images.githubusercontent.com/2502070/92166395-d6f23c00-ee38-11ea-811c-869bdfbbf057.png)

This has to be fixed by Hetzner as it happens in the API.

**Comment by timohirt** [comment]
Hetzner responded to bug report. Apparently, the API splits a string that is longer than 255 byte. That's required by the [DNS spec](https://tools.ietf.org/html/rfc4408#section-3.1.3) and the API doesn't abstract from this technical detail. So, this must be handled in the provider :-(

**Comment by hardoverflow** [comment]
I run into the same issue with the dkim key. Is there anything new?

**Comment by martinseener** [comment]
The issue still exists as of today. Tried this example dkim entry: 
```
"DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=asuswebstorage.com; s=default; t=1572282571; bh=NFzBvJ/pEmf+yUHDd/Y7dYNH9pE+Bx6o95KcxhwFL78=; h=From:To:Subject:From; b=QwgINKqwcBu3GbeWm2Be81qXks6Pq9yMmDZl9C6mT8moXVBeokpEmDN+0RyZFiOmNH30kbe6HbS2lY3" "b1Pf726UH/V/0VAH0nigTuir4TWdN/IUePV+goQdEJ2+sDQ1fHlVjyyJCRwCiFiZpBIjhTBNN0vrgNJZ/gSLLOvq6k3s=" 
```
you also see it cutted :/

**Comment by martinseener** [comment]
Do you @timohirt have an idea how we could solve this?

**Comment by martinseener** [comment]
As the RFC says: `If a published record contains multiple strings, then the record MUST be treated as if those strings are concatenated together without adding spaces.`
it means to me, that the provider is adding this just right. The DNS resolver should treat both strings as one "later".
   
dig shows to me:
```
;; ANSWER SECTION:
dkim._domainkey.domain.com.	86400	IN	TXT	"DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=asuswebstorage.com; s=default; t=1572282571; bh=NFzBvJ/pEmf+yUHDd/Y7dYNH9pE+Bx6o95KcxhwFL78=; h=From:To:Subject:From; b=QwgINKqwcBu3GbeWm2Be81qXks6Pq9yMmDZl9C6mT8moXVBeokpEmDN+0RyZFiOmNH30kbe6HbS2lY3" "b1Pf726UH/V/0VAH0nigTuir4TWdN/IUePV+goQdEJ2+sDQ1fHlVjyyJCRwCiFiZpBIjhTBNN0vrgNJZ/gSLLOvq6k3s="

```

so this looks ok to me, doesn't it!?

**Comment by scbay** [comment]
Any solution to this yet?

**Comment by timohirt** [comment]
Thanks @martinseener 🙏

**Comment by scbay** [comment]
@martinseener, thanks for your reply. Do you may have any example for this?

**Comment by martinseener** [comment]
I don't have that thing up anymore but here: https://github.com/timohirt/terraform-provider-hetznerdns/issues/13#issuecomment-1032795778
I showed a REAL dig output from one of my domains I manage (just renamed the domain name of course). So I tested this and it worked and "dig" where able to read it properly.

I needed I can try to put another example back up for your own test - but you can probably do on your own too.
