### ISSUE TITLE
Add more examples to the doc

### ISSUE THREAD

**Issue by c33s** [timohirt/terraform-provider-hetznerdns#15]
a out of the box working example with everything needed to create a zone, a record and assign it to a host would be awesome (see #14 xD)

**Comment by timohirt** [comment]
Did you notice the examples in the docs? The [record](https://registry.terraform.io/providers/timohirt/hetznerdns/latest/docs/resources/hetznerdns_record) and [zone](https://registry.terraform.io/providers/timohirt/hetznerdns/latest/docs/resources/hetznerdns_zone) docs both have an example showing how to use them.

**Comment by c33s** [comment]
yes i noticed them, thank you. what i ment is that the first page example should be a full working real world copy and paste example. so no clicking around just copy and paste and you are good to go. what do you think about that?

**Comment by timohirt** [comment]
Yes, that's a good idea. I understand that the current example requires an already created zone (see [here](https://registry.terraform.io/providers/timohirt/hetznerdns/latest/docs)).

I would add another example which defines both, a zone and a record. It will never be copy and paste as I don't know the zone of a user. But I think that would be fair enough. What do you think?

**Comment by c33s** [comment]
what about a fill example with the zone name `example.com` so you don't need to know the zone names but it's still a working copy and paste example. 
also i would go for a full zone example including spf and mx record. such full examples are still the best documentation.

**Comment by JonasKop** [comment]
> what about a fill example with the zone name `example.com` so you don't need to know the zone names but it's still a working copy and paste example.
> also i would go for a full zone example including spf and mx record. such full examples are still the best documentation.

@timohirt I made some quick examples of how to use this plugin. What do you think? #21

**Comment by timohirt** [comment]
![gif](https://media.giphy.com/media/AeWoyE3ZT90YM/giphy.gif)

Merged the PR. Thank you for adding the examples. I'll release a new version of the provider shortly. Then the documentation on Terraform Registry will update as well.

**Comment by martinseener** [comment]
@timohirt I think you can close this issue :) Since we now use this provider too for about 50 domains with terraform and Gitlab, I could also add some more examples like CAA and so on. Let me know if you're interested.
