### ISSUE TITLE
Fake or real ALIAS record support

### ISSUE THREAD

**Issue by c33s** [timohirt/terraform-provider-hetznerdns#18]
powerdns supports a record type called `ALIAS` where you can add "CNAME"-like records for the root of a domain. 

``hcl
resource "powerdns_record" "example_at" {
  zone    = "example.at."
  name    = "example.at."
  type    = "ALIAS"
  ttl     = 300
  records = ["www.example.at."]
}
resource "powerdns_record" "www_example_at" {
  zone    = "example.at."
  name    = "www.example.at."
  type    = "CNAME"
  ttl     = 300
  records = ["host10.example.net."]
}
```

real alias support must be implemented by hetzner, so the alias will auto looked up on query but this provider could allow a fake alias record, where the correct ip will be queried on terraform run and then a regular `A` record will be created.

- https://doc.powerdns.com/authoritative/guides/alias.html
- https://kb.isc.org/docs/aa-01640
- https://support.dnsimple.com/articles/alias-record/

**Comment by timohirt** [comment]
Not sure what I can do here. If you would like to see alias support, Hetzer needs to add support for it in the first place, as you already stated.

**Comment by c33s** [comment]
maybe it's possible to build some kind of wrapper where the zone name is automagically looked up to an id (don't know the internas).

what i missed to say: thank you very much for you work and that you opensourced your provider.

**Comment by timohirt** [comment]
After reading the articles you listed in the first comment, I think this can't be implemented without support of the DNS provider. Or at least I can't, as I'm no DNS expert. Do you want to contribute support for `ALIAS` records? Otherwise I would close the issue.
