### ISSUE TITLE
Add importer to DNS Record resource

### ISSUE THREAD

**Issue by timohirt** [timohirt/terraform-provider-hetznerdns#2]
Import a DNS record by name.

https://github.com/timohirt/terraform-provider-hetznerdns/blob/master/hetznerdns/resource_record.go#L19

**Comment by svenstaro** [comment]
We're currently starting our migration onto this provider in Arch Linux and having this importer would certainly ease these efforts immensely. Do you think you can get to this somewhat soon so that we should hold up for now or should we go the painful route of creating new entries?

**Comment by timohirt** [comment]
At a first glance, it shouldn't be easy to (finally) implement this importer. I think I can implement it until end of next week. Can you wait until then?

**Comment by svenstaro** [comment]
Yep, we can definitely wait until then. Thanks!

**Comment by timohirt** [comment]
@svenstaro just released v1.1.0 which supports importing DNS records: https://registry.terraform.io/providers/timohirt/hetznerdns/latest

**Comment by svenstaro** [comment]
Thanks a ton!
