### ISSUE TITLE
Suggestion: Provide constants for Hetzner nameservers

### ISSUE THREAD

**Issue by ThomasLandauer** [timohirt/terraform-provider-hetznerdns#27]
I just created this in my `.ts` file:
```ts
locals {
    hetzner_ns1 = "helium.ns.hetzner.de."
    hetzner_ns2 = "hydrogen.ns.hetzner.com."
    hetzner_ns3 = "oxygen.ns.hetzner.com."
}
```
And besides asking myself if this is really the "correct" way to do it ;-) - The more important question is: I guess everybody doing DNS with Hetzner will need those nameservers, so is there a way you could distribute those values right inside the provider?

**Comment by timohirt** [comment]
Valid point! The names are more or less fixed or at least they don't change frequently. 

This project is open for contributions and I would assist with the PR :-)

**Comment by ThomasLandauer** [comment]
Sorry, but my knowledge of Go is zero ;-)
But if somebody else creates the first name server, I'm sure I could copy-paste the two others... *lol*

**Comment by ThomasLandauer** [comment]
This is now implemented in the successor of this project: https://registry.terraform.io/providers/germanbrew/hetznerdns/latest/docs/data-sources/nameservers
So I'm closing here.
