### ISSUE TITLE
Suggestion: Support IDNs

### ISSUE THREAD

**Issue by ThomasLandauer** [timohirt/terraform-provider-hetznerdns#28]
When the domain name contains an umlaut, I'm getting this error:

> Error: Error creating zone. API returned HTTP 422 Unprocessable Entity error with message: '422 Unprocessable Entity: invalid invalid character for domain name'

So I'm suggesting that you're including the conversion to punycode in the provider - especially since (after a quick search) I couldn't find a conversion function in Terraform, so right now the conversion has to be done outside of Terraform (i.e. manually).

**Comment by c33s** [comment]
as workaround you can try using external data provider

something like this should work
```
// returns json {"name": "......"}
data "external" "exaemple_com" {
  program = ["bash", "${local.bin_dir}/convert-umlauts.sh", "exämple.com"]
}

// access it with 
data.external.exaemple_com.result.name
```

**Comment by kimdre** [comment]
Hi, we created a new fork of this project as this one is no longer maintained and added a bunch of additional features including a built in function for IDN/Punycode support.  

You can find it here: https://registry.terraform.io/providers/germanbrew/hetznerdns/latest/docs/functions/idna

**Comment by timohirt** [comment]
https://github.com/timohirt/terraform-provider-hetznerdns/issues/70
