### ISSUE TITLE
Environment variable is not recognized

### ISSUE THREAD

**Issue by timbrd** [timohirt/terraform-provider-hetznerdns#3]
Hi,

I'm trying to set some dns records, which works well when being asked for my API Token by terraform, but I always get a 401 error when using the `HETZNER_DNS_API_TOKEN` environment variable.

```module.worker.hetznerdns_record.dns-a[1]: Creating...
module.worker.hetznerdns_record.dns-a[2]: Creating...
module.worker.hetznerdns_record.dns-a[0]: Creating...

Error: Error creating DNS record api.os: Error creating Record. HTTP status 401 unhandled

  on dns.tf line 91, in resource "hetznerdns_record" "dns_a_api":
  91: resource "hetznerdns_record" "dns_a_api" {



Error: Error creating DNS record api-int.os: Error creating Record. HTTP status 401 unhandled

  on dns.tf line 101, in resource "hetznerdns_record" "dns_a_api_int":
 101: resource "hetznerdns_record" "dns_a_api_int" {



Error: Error creating DNS record apps.os: Error creating Record. HTTP status 401 unhandled

  on dns.tf line 111, in resource "hetznerdns_record" "dns_a_apps":
 111: resource "hetznerdns_record" "dns_a_apps" {
```

Any idea why the error occurs? How am I supposed to debug the problem?

Thanks,
Tim

**Comment by timohirt** [comment]
Hey @timbrd! Thanks for reporting.

I think that HTTP 401 means there is something wrong with the API token. Probably a copy and paste error? I could only reproduce by using an invalid token (removed the last char of the API token).

However, I agree the error message is not useful. Will change this in the next version.

**Comment by timohirt** [comment]
I added a handler for 401 unauthorized errors. Now, you can see the message from the API why your request was rejected. I hope this helps.

```
Error: Error getting zone state. Error getting zone example.com: API return 401 Unauthorized with message: 'Invalid authentication credentials'. Double check your API key is still valid

  on .terraform/modules/server/main.tf line 7, in data "hetznerdns_zone" "dns_zone":
   7: data "hetznerdns_zone" "dns_zone" {
```
