### ISSUE TITLE
Cannot update to 1.2.0: Failed to query available provider packages

### ISSUE THREAD

**Issue by ThomasLandauer** [timohirt/terraform-provider-hetznerdns#33]
When I change the version from `1.1.1` to `1.2.0` at
```terraform
        hetznerdns = {
            source = "timohirt/hetznerdns"
            version = "1.2.0"
        }
```
... and run `terraform init -upgrade`, I'm getting:
```
Initializing provider plugins...
- Finding hetznercloud/hcloud versions matching "1.32.2"...
- Finding timohirt/hetznerdns versions matching "1.1.1, 1.2.0"...
- Using previously-installed hetznercloud/hcloud v1.32.2
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider timohirt/hetznerdns: no available releases match the given constraints 1.1.1, 1.2.0
```

**Comment by Xzelsius** [comment]
I get a similar error

```
Initializing provider plugins...
- Reusing previous version of hashicorp/azurerm from the dependency lock file
- Reusing previous version of timohirt/hetznerdns from the dependency lock file
- Finding latest version of hashicorp/hetznerdns...
- Installing hashicorp/azurerm v2.92.0...
- Installed hashicorp/azurerm v2.92.0 (signed by HashiCorp)
- Installing timohirt/hetznerdns v1.1.0...
- Installed timohirt/hetznerdns v1.1.0 (self-signed, key ID 5218E983F21C1625)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider
│ hashicorp/hetznerdns: provider registry registry.terraform.io does not have
│ a provider named registry.terraform.io/hashicorp/hetznerdns
```

Fun part actually... If I check providers

```
❯ terraform providers

Providers required by configuration:
.
├── provider[registry.terraform.io/timohirt/hetznerdns] 1.1.0
├── provider[registry.terraform.io/hashicorp/azurerm] >= 2.92.0
├── module.azure
│   └── provider[registry.terraform.io/hashicorp/azurerm]
└── module.hdns
    └── provider[registry.terraform.io/hashicorp/hetznerdns]
```

Although the only resource in module.hdns is

```
resource "hetznerdns_zone" "example.com" {
  name = "example.com"
  ttl  = var.default_ttl
}
```

Any idea on how to solve this issue?
Happens with both, 1.1.1 and 1.2.0

**Comment by timohirt** [comment]
>  Could not retrieve the list of available versions for provider
│ hashicorp/hetznerdns: provider registry registry.terraform.io does not have
│ a provider named registry.terraform.io/hashicorp/hetznerdns

@Xzelsius that's correct. The provider should be `timohirt/hetznerdns` and not `hashicorp/hetznerdns`. Ich you don't find `hashicorp/hetznerdns` in your code, would you please check your state file?

**Comment by Xzelsius** [comment]
I am using a child module structure.
And I did miss the part in the documentation where I have to specify `required_providers` in the child module again (unless it is a `hashicorp/...` provider).

![image](https://user-images.githubusercontent.com/17022099/150024751-c3ca81ac-83c0-4a1c-85e9-bba8214c157c.png)

I simply added another meta.tf file (red arrow) with

```
terraform {
  required_providers {
    hetznerdns = {
      source  = "timohirt/hetznerdns"
      version = "1.2.0"
    }
  }
}
```

Now it works as expected :)

**Comment by timohirt** [comment]
That's good to hear 🙂.

How about you @ThomasLandauer?

**Comment by ThomasLandauer** [comment]
Thanks guys, I also didn't know that I need to upgrade the version in each module.
Is there a better way to do this than just copy-pasting? I have several modules based on this provider, but they're all independent (no child modules), so just creating a `meta.tf` didn't work.
