### ISSUE TITLE
Suggestion: Hand over the project to https://github.com/hetznercloud GitHub organization

### ISSUE THREAD

**Issue by icepuma** [timohirt/terraform-provider-hetznerdns#44]
Hey,

you did an awesome job. Your terraform provider helped me a lot setting up my infrastructure.
I would love to see this project flourish. 

From the age of the tickets I derive that you don't have much time right now to maintain this project. Correct me if I'm wrong :)

Handing over your project to https://github.com/hetznercloud would help the folks over at Hetzner to govern everything regarding their cloud products under one umbrella.

If you don't like the idea oder I'm totally wrong, just close the ticket.

Best regards and a nice weekend
Stefan

**Comment by timohirt** [comment]
I'm happy with handing over the project. Not sure who to talk to tbh. @LKaemmerling maybe?

**Comment by icepuma** [comment]
Yeah. From what I've read on Twitter he seems to be a nice guy and I think he would be the right person to contact :+1:

**Comment by kimdre** [comment]
I like the idea as well. 👍 There is also a lot of activity there.

**Comment by jkroepke** [comment]
Since we are heavily using the provider in our business, we decide to fork the provider in our own: https://github.com/germanbrew/terraform-provider-hetznerdns

**Comment by timohirt** [comment]
Thanks for taking core of it @jkroepke and @kimdre. Much appreciated :-)
