### ISSUE TITLE
Add the ability to manage primary servers

### ISSUE THREAD

**Issue by Frisch12** [timohirt/terraform-provider-hetznerdns#45]
Would be nice if there were a resource for managing primary servers. 

Look here: https://dns.hetzner.com/api-docs/#operation/GetPrimaryServers

**Comment by Frisch12** [comment]
Look at my PR #46

**Comment by timohirt** [comment]
There you go @Frisch12 https://github.com/timohirt/terraform-provider-hetznerdns/releases/tag/v2.2.0

**Comment by Frisch12** [comment]
Whooohoo. Thank you very much :)
