### ISSUE TITLE
Convert list of values to multiple records

### ISSUE THREAD

**Issue by kimdre** [timohirt/terraform-provider-hetznerdns#51]
I would love to have the abillity to use lists to generate (multiple) records like so for example:

```tf
resource "hetznerdns_record" "domain_com-NS" {
  zone_id = hetznerdns_zone.domain_com.id
  name = "@"
  type = "NS"
  value = [ "helium.ns.hetzner.de.", "hydrogen.ns.hetzner.com.", "oxygen.ns.hetzner.com." ]
```

**Comment by ThomasLandauer** [comment]
Looks like you already implemented this at https://github.com/germanbrew/terraform-provider-hetznerdns/issues/23
But for this concrete example, the way to go is https://registry.terraform.io/providers/germanbrew/hetznerdns/latest/docs/data-sources/nameservers
In any case, I think you can close this issue as "not planned" here.
