### ISSUE TITLE
Long TXT value is getting recreated upon `terraform apply`

### ISSUE THREAD

**Issue by ThomasLandauer** [timohirt/terraform-provider-hetznerdns#54]
I have this DKIM record in my `terraform.tf`:
```terraform
value  = "v=DKIM1;h=sha256;k=rsa;s=email;p=MIIB...QAB""
```

Now, upon each `terraform apply`, I'm getting:

```
# hetznerdns_record.... will be updated in-place
~ resource "hetznerdns_record" "..." {
      id      = "..."
      name    = "default._domainkey.mail"
    ~ value   = "\"v=DKIM1;h=sha256;k=rsa;s=email;p=MIIB...rui\" \"6AD...QAB\" " -> "v=DKIM1;h=sha256;k=rsa;s=email;p=MIIB...QAB\""
      # (3 unchanged attributes hidden)
  }
```

So (together with the information from https://github.com/timohirt/terraform-provider-hetznerdns/issues/13) this looks like the API is automatically splitting the long string. But then, this provider thinks it's different from my long string, and tries to recreate it.
Unfortunately, I didn't quite get the bottom line of https://github.com/timohirt/terraform-provider-hetznerdns/issues/13 - is it to split the `value` string *manually* in 2 parts?

**Comment by ThomasLandauer** [comment]
@kimdre Sorry, I edited the question a lot after your comment. But in any case: I just tried `jsconencode`, and it doesn't make a difference.

**Comment by kimdre** [comment]
The splitting is normal for long records like dkim, as the length of single string in TXT records is [limited to 255 bytes](https://github.com/timohirt/terraform-provider-hetznerdns/issues/13#issuecomment-687865996). It's normal though and the only workaround for this is to replace your single string with the splitted one that terraform shows as the current value before performing actions.

**Comment by kimdre** [comment]
A nice workaround to split recods automatically is described in a similiar issue related to route53 by aws https://github.com/hashicorp/terraform-provider-aws/issues/14941#issuecomment-744591440

**Comment by ThomasLandauer** [comment]
Thanks, here's what I came up with after some trial and error: https://github.com/timohirt/terraform-provider-hetznerdns/pull/56
`jsonencode` takes care of escaping the quotes, and the last `""` is to get the blank character at the end.
Do you see a nicer way?

**Comment by ThomasLandauer** [comment]
Oh, I've overlooked that. However, it's overescaping (`\"\"`), so `jsonencode` would probably be required as well.
Anyway, I've already spent too much time for this - if anybody finds a cleaner solution, feel free to update my example in README! :-)

**Comment by ThomasLandauer** [comment]
Indeed, this works for me too. I added it as alternative way - since it isn't really simpler than the other way ;-)
