### ISSUE TITLE
Submit provider gpg key to registry.opentofu.org

### ISSUE THREAD

**Issue by jkroepke** [timohirt/terraform-provider-hetznerdns#63]
Hi @timohirt 

if possible, please submit your gpg public key to https://github.com/opentofu/registry/issues/new?assignees=&labels=provider-key%2Csubmission&projects=&template=provider_key.yml&title=Provider+Key%3A+

At the moment, tofu eco system is unable to verify the gpg key for the provider. Currently, skipping verification is enabled by default, but I guess in future its manatory.

**Comment by kimdre** [comment]
We now maintain an updated fork of this project that supports both Terraform and OpenTofu:  https://github.com/germanbrew/terraform-provider-hetznerdns
