### ISSUE TITLE
Consider allowing HETZNER_DNS_TOKEN as env var as well

### ISSUE THREAD

**Issue by flortsch** [timohirt/terraform-provider-hetznerdns#65]
Hello!

I would like to make the suggestion to also allow the env var `HETZNER_DNS_TOKEN` for setting the Hetzner DNS API token.

We are using Terraform together with Ansible and its Hetzner DNS community module (https://docs.ansible.com/ansible/latest/collections/community/dns/docsite/hetzner_guide.html) that uses this env var for setting the token. By using the same env var, we could 
only need to configure the token once.

This would also align with the Hetzner Terraform provider (https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs) and the Ansible Hetzner Cloud inventory plugin (https://docs.ansible.com/ansible/latest/collections/hetzner/hcloud/hcloud_inventory.html) or parts of the Ansible Hetzner collection in general, which all use the same env var `HCLOUD_TOKEN`.

What do you think?

**Comment by kimdre** [comment]
Hi, this provider is no longer maintained. 
You can open an issue or pull request for our new provider instead: https://github.com/germanbrew/terraform-provider-hetznerdns

Alternatively you could specify your api token in a .env file and use the [dotenv provider](https://registry.terraform.io/providers/germanbrew/dotenv/latest/docs).

**Comment by flortsch** [comment]
> Hi, this provider is no longer maintained. You can open an issue or pull request for our new provider instead: https://github.com/germanbrew/terraform-provider-hetznerdns
> 
> Alternatively you could specify your api token in a .env file and use the [dotenv provider](https://registry.terraform.io/providers/germanbrew/dotenv/latest/docs).

Ah okay, didn't know that. Maybe a note in the README of this Github project would help future users. I will open an issue in the new project.

**Comment by kimdre** [comment]
Timo is the only one who maintains this repo, but unfortunately he no longer works on it and also doesn't respond to messages. That's the reason why we forked this repo.

**Comment by timohirt** [comment]
@flortsch added it to the README. I'm still open for contributions if it is still relevant for you. However, I'm not actively developing this provider.
