### ISSUE TITLE
terraform 0.13 support

### ISSUE THREAD

**Issue by DanielMSchmidt** [timohirt/terraform-provider-hetznerdns#8]
Hey there,
first of all big thanks for this great module!

I tried to install it in a terraform 0.13 environment where they changed the way you install plugins and I don't understand the [hostname part that should be used for this provider](https://www.terraform.io/upgrade-guides/0-13.html#new-filesystem-layout-for-local-copies-of-providers).
Any ideas where one would need to put the plugins with 0.13?

**Comment by timohirt** [comment]
Hey @DanielMSchmidt 

Thanks for reporting this issue. I was able to reproduce and documented how to fix it.

- First install the provider using the new directory structure: https://github.com/timohirt/terraform-provider-hetznerdns/blob/main/INSTALL.md#terraform-013
- Then put the provider source location in the terraform configuration of your project:
https://github.com/timohirt/terraform-provider-hetznerdns#set-provider-source-location-terraform-013

Looking forward to your feedback.

**Comment by timohirt** [comment]
@DanielMSchmidt this provider is now available in Terraform registry: https://registry.terraform.io/providers/timohirt/hetznerdns/latest

**Comment by DanielMSchmidt** [comment]
Awesome, thanks a ton 👍
